/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'message' : string,
}
export interface Course {
  'id' : bigint,
  'title' : string,
  'instructor' : string,
  'description' : string,
  'schedule' : string,
}
export interface StudentProfile {
  'age' : bigint,
  'tuitionCenter' : string,
  'dateOfBirth' : string,
  'school' : string,
  'name' : string,
  'profilePhoto' : string,
  'studentMobileNumber' : [] | [string],
  'parentMobileNumber' : string,
  'batch' : string,
  'className' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[string, string, string], undefined>,
  'createCourse' : ActorMethod<[string, string, string, string], undefined>,
  'createStudentProfile' : ActorMethod<[StudentProfile], undefined>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllStudentProfiles' : ActorMethod<[], Array<[Principal, StudentProfile]>>,
  'getCallerRole' : ActorMethod<[], string>,
  'getCallerStudentProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactDetails' : ActorMethod<[], [string, string, string]>,
  'getLogo' : ActorMethod<[], Uint8Array>,
  'getStudentProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'getUserRole' : ActorMethod<[Principal], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateAnnouncement' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'updateContactDetails' : ActorMethod<[string, string, string], undefined>,
  'updateCourse' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateLogo' : ActorMethod<[Uint8Array], undefined>,
  'updateStudentProfile' : ActorMethod<[Principal, StudentProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];