/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudentProfile = IDL.Record({
  'age' : IDL.Nat,
  'tuitionCenter' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'school' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Vec(IDL.Nat8),
  'studentMobileNumber' : IDL.Opt(IDL.Text),
  'parentMobileNumber' : IDL.Text,
  'batch' : IDL.Text,
  'className' : IDL.Text,
});
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'message' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'instructor' : IDL.Text,
  'description' : IDL.Text,
  'schedule' : IDL.Text,
  'monthlyFee' : IDL.Nat,
});
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceEntry = IDL.Record({
  'status' : AttendanceStatus,
  'date' : Time,
});
export const AttendanceDay = IDL.Record({
  'day' : IDL.Nat,
  'status' : AttendanceStatus,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
});
export const EnrollmentStatus = IDL.Variant({
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const EnrollmentRequest = IDL.Record({
  'status' : EnrollmentStatus,
  'expiryDate' : IDL.Opt(Time),
  'approvalDate' : IDL.Opt(Time),
  'student' : IDL.Principal,
  'renewalRequest' : IDL.Bool,
  'requestDate' : Time,
  'courseId' : IDL.Nat,
});
export const TestResult = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'pass' : IDL.Bool,
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'grade' : IDL.Text,
  'student' : IDL.Principal,
  'courseId' : IDL.Nat,
});
export const DailyResult = IDL.Record({
  'date' : Time,
  'score' : IDL.Nat,
  'student' : IDL.Principal,
  'resultType' : IDL.Text,
  'courseId' : IDL.Nat,
  'remarks' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveEnrollment' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'approveRenewal' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createCourse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createStudentProfile' : IDL.Func([StudentProfile], [], []),
  'createTestResult' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool, IDL.Text, Time],
      [],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllStudentProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, StudentProfile))],
      ['query'],
    ),
  'getAttendanceByDateRange' : IDL.Func(
      [IDL.Principal, Time, Time],
      [IDL.Vec(AttendanceEntry)],
      ['query'],
    ),
  'getAttendanceForMonth' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Vec(AttendanceDay)],
      ['query'],
    ),
  'getCallerAttendance' : IDL.Func([], [IDL.Vec(AttendanceEntry)], ['query']),
  'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerStudentProfile' : IDL.Func(
      [],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactDetails' : IDL.Func([], [IDL.Text, IDL.Text, IDL.Text], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCoursesWithEnrollmentStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'courses' : IDL.Vec(Course),
          'expiredEnrollments' : IDL.Vec(IDL.Nat),
          'activeEnrollments' : IDL.Vec(IDL.Nat),
          'enrollmentRequests' : IDL.Vec(IDL.Nat),
        }),
      ],
      ['query'],
    ),
  'getEnrollmentsByCourse' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EnrollmentRequest)],
      ['query'],
    ),
  'getEnrollmentsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EnrollmentRequest)],
      ['query'],
    ),
  'getLogo' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
  'getResultsByCourse' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'testResults' : IDL.Vec(TestResult),
          'dailyResults' : IDL.Vec(DailyResult),
        }),
      ],
      ['query'],
    ),
  'getResultsByDate' : IDL.Func(
      [Time],
      [
        IDL.Record({
          'testResults' : IDL.Vec(TestResult),
          'dailyResults' : IDL.Vec(DailyResult),
        }),
      ],
      ['query'],
    ),
  'getResultsByStudent' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'testResults' : IDL.Vec(TestResult),
          'dailyResults' : IDL.Vec(DailyResult),
        }),
      ],
      ['query'],
    ),
  'getStudentAttendance' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AttendanceEntry)],
      ['query'],
    ),
  'getStudentProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Principal, Time, AttendanceStatus], [], []),
  'postDailyResult' : IDL.Func(
      [IDL.Principal, IDL.Nat, Time, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'rejectEnrollment' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'renewEnrollment' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'requestEnrollment' : IDL.Func([IDL.Nat], [], []),
  'requestRenewal' : IDL.Func([IDL.Nat], [], []),
  'updateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateContactDetails' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateCourse' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateDailyResult' : IDL.Func(
      [IDL.Principal, IDL.Nat, Time, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateLogo' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'updateStudentProfile' : IDL.Func([IDL.Principal, StudentProfile], [], []),
  'updateTestResult' : IDL.Func(
      [
        IDL.Nat,
        IDL.Principal,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        Time,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudentProfile = IDL.Record({
    'age' : IDL.Nat,
    'tuitionCenter' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'school' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Vec(IDL.Nat8),
    'studentMobileNumber' : IDL.Opt(IDL.Text),
    'parentMobileNumber' : IDL.Text,
    'batch' : IDL.Text,
    'className' : IDL.Text,
  });
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'message' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'instructor' : IDL.Text,
    'description' : IDL.Text,
    'schedule' : IDL.Text,
    'monthlyFee' : IDL.Nat,
  });
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceEntry = IDL.Record({
    'status' : AttendanceStatus,
    'date' : Time,
  });
  const AttendanceDay = IDL.Record({
    'day' : IDL.Nat,
    'status' : AttendanceStatus,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const EnrollmentStatus = IDL.Variant({
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const EnrollmentRequest = IDL.Record({
    'status' : EnrollmentStatus,
    'expiryDate' : IDL.Opt(Time),
    'approvalDate' : IDL.Opt(Time),
    'student' : IDL.Principal,
    'renewalRequest' : IDL.Bool,
    'requestDate' : Time,
    'courseId' : IDL.Nat,
  });
  const TestResult = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'pass' : IDL.Bool,
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'grade' : IDL.Text,
    'student' : IDL.Principal,
    'courseId' : IDL.Nat,
  });
  const DailyResult = IDL.Record({
    'date' : Time,
    'score' : IDL.Nat,
    'student' : IDL.Principal,
    'resultType' : IDL.Text,
    'courseId' : IDL.Nat,
    'remarks' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveEnrollment' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'approveRenewal' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createCourse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createStudentProfile' : IDL.Func([StudentProfile], [], []),
    'createTestResult' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool, IDL.Text, Time],
        [],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllStudentProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, StudentProfile))],
        ['query'],
      ),
    'getAttendanceByDateRange' : IDL.Func(
        [IDL.Principal, Time, Time],
        [IDL.Vec(AttendanceEntry)],
        ['query'],
      ),
    'getAttendanceForMonth' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Vec(AttendanceDay)],
        ['query'],
      ),
    'getCallerAttendance' : IDL.Func([], [IDL.Vec(AttendanceEntry)], ['query']),
    'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerStudentProfile' : IDL.Func(
        [],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactDetails' : IDL.Func(
        [],
        [IDL.Text, IDL.Text, IDL.Text],
        ['query'],
      ),
    'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCoursesWithEnrollmentStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'courses' : IDL.Vec(Course),
            'expiredEnrollments' : IDL.Vec(IDL.Nat),
            'activeEnrollments' : IDL.Vec(IDL.Nat),
            'enrollmentRequests' : IDL.Vec(IDL.Nat),
          }),
        ],
        ['query'],
      ),
    'getEnrollmentsByCourse' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EnrollmentRequest)],
        ['query'],
      ),
    'getEnrollmentsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EnrollmentRequest)],
        ['query'],
      ),
    'getLogo' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
    'getResultsByCourse' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'testResults' : IDL.Vec(TestResult),
            'dailyResults' : IDL.Vec(DailyResult),
          }),
        ],
        ['query'],
      ),
    'getResultsByDate' : IDL.Func(
        [Time],
        [
          IDL.Record({
            'testResults' : IDL.Vec(TestResult),
            'dailyResults' : IDL.Vec(DailyResult),
          }),
        ],
        ['query'],
      ),
    'getResultsByStudent' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'testResults' : IDL.Vec(TestResult),
            'dailyResults' : IDL.Vec(DailyResult),
          }),
        ],
        ['query'],
      ),
    'getStudentAttendance' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AttendanceEntry)],
        ['query'],
      ),
    'getStudentProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [IDL.Principal, Time, AttendanceStatus],
        [],
        [],
      ),
    'postDailyResult' : IDL.Func(
        [IDL.Principal, IDL.Nat, Time, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'rejectEnrollment' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'renewEnrollment' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'requestEnrollment' : IDL.Func([IDL.Nat], [], []),
    'requestRenewal' : IDL.Func([IDL.Nat], [], []),
    'updateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateContactDetails' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateCourse' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateDailyResult' : IDL.Func(
        [IDL.Principal, IDL.Nat, Time, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateLogo' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'updateStudentProfile' : IDL.Func([IDL.Principal, StudentProfile], [], []),
    'updateTestResult' : IDL.Func(
        [
          IDL.Nat,
          IDL.Principal,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          Time,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };