/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudentProfile = IDL.Record({
  'age' : IDL.Nat,
  'tuitionCenter' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'school' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Text,
  'studentMobileNumber' : IDL.Opt(IDL.Text),
  'parentMobileNumber' : IDL.Text,
  'batch' : IDL.Text,
  'className' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'message' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'instructor' : IDL.Text,
  'description' : IDL.Text,
  'schedule' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'createStudentProfile' : IDL.Func([StudentProfile], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllStudentProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, StudentProfile))],
      ['query'],
    ),
  'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerStudentProfile' : IDL.Func(
      [],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactDetails' : IDL.Func([], [IDL.Text, IDL.Text, IDL.Text], ['query']),
  'getLogo' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
  'getStudentProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateContactDetails' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateCourse' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateLogo' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'updateStudentProfile' : IDL.Func([IDL.Principal, StudentProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudentProfile = IDL.Record({
    'age' : IDL.Nat,
    'tuitionCenter' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'school' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Text,
    'studentMobileNumber' : IDL.Opt(IDL.Text),
    'parentMobileNumber' : IDL.Text,
    'batch' : IDL.Text,
    'className' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'message' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'instructor' : IDL.Text,
    'description' : IDL.Text,
    'schedule' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'createStudentProfile' : IDL.Func([StudentProfile], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllStudentProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, StudentProfile))],
        ['query'],
      ),
    'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerStudentProfile' : IDL.Func(
        [],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactDetails' : IDL.Func(
        [],
        [IDL.Text, IDL.Text, IDL.Text],
        ['query'],
      ),
    'getLogo' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
    'getStudentProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateContactDetails' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateCourse' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateLogo' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'updateStudentProfile' : IDL.Func([IDL.Principal, StudentProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };